# Company API

### Get company
GET http://localhost:1994/proxy/api/company?companyId=01JT8ZS5D8YDT3ZVZWKNG1423H

### Create a new company
PUT http://localhost:1994/proxy/api/company
Content-Type: application/json

{
  "name": "Test Company 2"
}

### Delete a company
DELETE http://localhost:1994/proxy/api/company?companyId=01JT91MNF31P5N1ZYG954SKZWM
