name: Changelog
on:
  push:
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHGLOG_VERSION: "0.15.4"

jobs:
  changelog:
    name: "Changelog"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.PUSH_MASTER_SECRET_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Install git-chglog
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v${{ env.CHGLOG_VERSION }}/git-chglog_${{ env.CHGLOG_VERSION }}_linux_amd64.tar.gz
          tar -xzf git-chglog_${{ env.CHGLOG_VERSION }}_linux_amd64.tar.gz
          sudo mv git-chglog /usr/local/bin/
          rm git-chglog_${{ env.CHGLOG_VERSION }}_linux_amd64.tar.gz

      - name: Fetch All Tags
        run: git fetch --tags --force

      - name: Generate CHANGELOG
        id: generate_changelog
        run: |
          current_tag=${GITHUB_REF#refs/tags/}
          git-chglog -o CHANGELOG.md "v0.0.1..$current_tag"

      - name: Commit to Master
        uses: EndBug/add-and-commit@v9
        with:
          author_name: OpenHotel Actions
          author_email: actions@openhotel.club
          message: "chore: update CHANGELOG for ${{ github.ref_name }}"
          add: CHANGELOG.md
          branch: master
          push: true
          token: ${{ secrets.PUSH_MASTER_SECRET_TOKEN || secrets.GITHUB_TOKEN }}
