name: Check Storybook
on:
  push:
    branches: [master]
    paths:
      - .github/**
      - app/client/**
  pull_request:
    paths:
      - .github/**
      - app/client/**

jobs:
  storybook-check:
    name: "Check Storybook"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x.x

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: deno task install:client

      - name: Build
        run: deno task check-storybook
